const state={history:[],ranked:[],weather:[],selected:null,recurringOnly:true,filters:{region:'all',freq:'all',mechanism:'all'},window:{start:2558,end:2568,years:11}};
const $=s=>document.querySelector(s);
const fmt=(n,d=0)=>n==null?'ไม่มีข้อมูลยืนยัน':Number(n).toLocaleString('th-TH',{maximumFractionDigits:d});
const normalize=s=>(s||'').toLowerCase().trim();
const project=(lat,lon)=>{const minLat=5.4,maxLat=20.6,minLon=97.2,maxLon=105.8;return [80+((lon-minLon)/(maxLon-minLon))*460,650-((lat-minLat)/(maxLat-minLat))*585]};
const recurrenceColor=n=>n>=7?'#c93648':n>=5?'#e96c35':n>=4?'#e8a51c':'#93a3b2';
function getWeather(name){return state.weather.find(x=>x.name===name)}
function mechanismKey(list=[]){const s=list.join(' ');if(/เมือง|ระบาย/.test(s))return 'urban';if(/ล้นตลิ่ง|แม่น้ำ|ลุ่ม/.test(s))return 'river';if(/น้ำป่า|หลาก|ดินถล่ม/.test(s))return 'flash';return 'other'}
async function loadAll(force=false){$('#errorBanner').hidden=true;$('#refreshBtn').disabled=true;try{const qs=force?`?t=${Date.now()}`:'';const [h,w]=await Promise.all([fetch('/api/history'+qs,{cache:force?'no-store':'default'}).then(r=>r.json()),fetch('/api/forecast'+qs,{cache:force?'no-store':'default'}).then(r=>r.json()).catch(()=>({ok:false,provinces:[]}))]);if(!h.ok)throw new Error(h.error||'โหลดข้อมูลประวัติไม่สำเร็จ');state.history=h.provinces||[];state.ranked=h.ranked||[];state.window=h.window||state.window;state.weather=w.ok?(w.provinces||[]):[];const saved=localStorage.getItem('thaiflood:intel:selected');state.selected=state.history.find(x=>x.name===saved)||state.history.find(x=>x.name==='เชียงใหม่')||state.ranked[0]||state.history[0];renderAll();if(!w.ok){$('#errorBanner').hidden=false;$('#errorText').textContent='ข้อมูลประวัติทำงานปกติ แต่สัญญาณฝนล่าสุดยังโหลดไม่ได้'}}catch(e){$('#errorBanner').hidden=false;$('#errorText').textContent=e.message||'กรุณาลองใหม่'}finally{$('#refreshBtn').disabled=false}}
function filteredRanked(){return state.ranked.filter(p=>{if(state.filters.region!=='all'&&p.region!==state.filters.region)return false;if(state.filters.freq!=='all'&&Number(p.recurrence||0)<Number(state.filters.freq))return false;if(state.filters.mechanism!=='all'&&mechanismKey(p.mechanisms)!==state.filters.mechanism)return false;return true})}
function renderAll(){renderStats();renderRanking();renderMap();renderProvince();renderSearch('')}
function renderStats(){const ranked=state.ranked;$('#repeatAreaCount').textContent=fmt(ranked.length);$('#maxRecurrence').textContent=fmt(Math.max(0,...ranked.map(x=>x.recurrence||0)));$('#topProvince').textContent=ranked[0]?.name||'—';$('#topProvinceMeta').textContent=ranked[0]?`${ranked[0].recurrence} ครั้ง / 11 ปี`:'—';$('#maxRainToday').textContent=state.weather.length?fmt(Math.max(...state.weather.map(x=>Number(x.rain24||0))),1):'—'}
function renderRanking(){const box=$('#rankingList');box.innerHTML='';const rows=filteredRanked();if(!rows.length){box.innerHTML='<div class="empty-text">ไม่พบพื้นที่ตามตัวกรอง</div>';return}rows.forEach((p,i)=>{const b=document.createElement('button');b.className=`rank-row ${state.selected?.name===p.name?'selected':''}`;b.innerHTML=`<span class="rank-no">${String(i+1).padStart(2,'0')}</span><span><b>${p.name}</b><small>ภาค${p.region}${p.hotspots.length?' • '+p.hotspots.join(', '):''}</small></span><span class="freq-pill">${p.recurrence} ครั้ง</span>`;b.onclick=()=>selectProvince(p.name,true);box.appendChild(b)})}
function renderMap(){const svg=$('#historyMap');svg.innerHTML='<path class="map-outline" d="M311 42 C338 75 360 106 355 144 C348 190 395 213 389 251 C381 300 414 319 438 353 C462 387 449 425 422 457 C391 494 405 532 435 574 C455 602 441 646 406 663 C377 676 350 646 336 618 C316 579 286 552 273 511 C259 466 242 437 219 401 C195 363 175 326 176 287 C178 245 206 216 230 187 C252 160 245 128 257 96 C269 66 286 47 311 42 Z"/>';filteredRanked().forEach(p=>{const [x,y]=project(p.lat,p.lon),ns='http://www.w3.org/2000/svg';const g=document.createElementNS(ns,'g');const c=document.createElementNS(ns,'circle');const r=7+(p.recurrence-4)*3;c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r',Math.max(7,r));c.setAttribute('fill',recurrenceColor(p.recurrence));c.setAttribute('class',`history-dot ${state.selected?.name===p.name?'selected':''}`);c.innerHTML=`<title>${p.name} • ${p.recurrence} ครั้ง / 11 ปี</title>`;c.onclick=()=>selectProvince(p.name,true);g.appendChild(c);if(state.selected?.name===p.name){const t=document.createElementNS(ns,'text');t.setAttribute('x',x+14);t.setAttribute('y',y+4);t.setAttribute('class','history-label');t.textContent=p.name;g.appendChild(t)}svg.appendChild(g)})}
function renderProvince(){const p=state.selected;if(!p)return;const w=getWeather(p.name);$('#selectedName').textContent=p.name;$('#selectedRegion').textContent=`ภาค${p.region}`;$('#recurrenceBadge').innerHTML=`<small>ท่วมซ้ำ</small><strong>${p.recurrence==null?'—':p.recurrence}</strong><span>${p.recurrence==null?'ไม่มีข้อมูลยืนยัน':'ครั้ง / 11 ปี'}</span>`;$('#metricRecurrence').textContent=p.recurrence==null?'—':p.recurrence;const events=p.events||[];const knownWater=events.map(e=>e.maxWaterM).filter(v=>v!=null),knownDamage=events.map(e=>e.damageM).filter(v=>v!=null),knownAid=events.map(e=>e.aidM).filter(v=>v!=null);$('#metricWater').textContent=knownWater.length?fmt(Math.max(...knownWater),1):'—';$('#metricDamage').textContent=knownDamage.length?fmt(knownDamage.reduce((a,b)=>a+b,0)):'—';$('#metricAid').textContent=knownAid.length?fmt(knownAid.reduce((a,b)=>a+b,0)):'—';renderTags($('#hotspotTags'),p.hotspots,true);renderTags($('#mechanismTags'),p.mechanisms,false);$('#patternInsight').textContent=patternInsight(p,w);renderYears(p);renderSignals(w);renderConfidence(p);renderRanking();renderMap()}
function renderTags(el,arr,emphasis=false){el.innerHTML='';if(!arr?.length){el.innerHTML='<span class="empty-text">ยังไม่มีข้อมูลยืนยันในชุดอ้างอิง</span>';return}arr.forEach(x=>{const s=document.createElement('span');s.className=`tag ${emphasis?'emphasis':''}`;s.textContent=x;el.appendChild(s)})}
function patternInsight(p,w){if(p.recurrence==null)return 'จังหวัดนี้ยังไม่มีค่าความถี่ที่ยืนยันในชุดข้อมูลต้นแบบ จึงไม่ควรสรุปว่า “ไม่เคยท่วม” ต้องเชื่อมฐานข้อมูลเหตุการณ์จริงเพิ่มเติม';let t=`มีการบันทึกน้ำท่วมซ้ำ ${p.recurrence} ครั้งในช่วง 11 ปี จึงควรถูกจัดเป็นพื้นที่เฝ้าระวังเชิงประวัติ ไม่ควรรอให้ฝนตกหนักก่อนจึงเริ่มเตรียมการ`;if(w&&w.rain3>=40)t+=` ขณะเดียวกันฝนสะสม 3 วันล่าสุดอยู่ที่ ${fmt(w.rain3,1)} มม. จึงควรซ้อนข้อมูลระดับน้ำและทางระบายเพื่อประเมินสถานการณ์ปัจจุบัน`;return t}
function renderYears(p){const box=$('#yearMatrix');box.innerHTML='';for(let y=state.window.start;y<=state.window.end;y++){const ev=(p.events||[]).find(e=>e.year===y);const d=document.createElement('div');d.className=`year-cell ${ev?'has-event':''}`;d.innerHTML=`<b>${String(y).slice(-2)}</b><span>${ev?'มีข้อมูล':'—'}</span>`;box.appendChild(d)}const details=$('#eventDetails');details.innerHTML='';if(!(p.events||[]).length){details.innerHTML='<div class="empty-text">ชุดต้นแบบระบุจำนวนครั้ง แต่ไม่ได้เปิดเผยรายละเอียดรายปีของจังหวัดนี้ครบทุกเหตุการณ์ — ระบบจึงไม่สร้างปีหรือความเสียหายขึ้นเอง</div>';return}p.events.forEach(e=>{const c=document.createElement('div');c.className='event-card';c.innerHTML=`<h4>พ.ศ. ${e.year} • ${e.severity==='critical'?'วิกฤต':'เหตุการณ์ที่บันทึก'}</h4><p>ระดับน้ำสูงสุด: <strong>${fmt(e.maxWaterM,1)} เมตร</strong></p><p>ความเสียหายรวม: <strong>${fmt(e.damageM)} ล้านบาท</strong></p><p>งบช่วยเหลือรวม: <strong>${fmt(e.aidM)} ล้านบาท</strong></p><p>${e.note||''}</p>`;details.appendChild(c)})}
function renderSignals(w){if(!w){['rain24','rain3','rainProb','rainScore'].forEach(id=>$('#'+id).textContent='—');$('#sevenDayBars').innerHTML='<span class="empty-text">ยังโหลดสัญญาณฝนล่าสุดไม่ได้</span>';return}$('#rain24').textContent=fmt(w.rain24,1);$('#rain3').textContent=fmt(w.rain3,1);$('#rainProb').textContent=fmt(w.probability);$('#rainScore').textContent=fmt(w.score);const values=w.sevenDayRain||[],max=Math.max(10,...values);$('#sevenDayBars').innerHTML='';values.slice(0,7).forEach((v,i)=>{const d=document.createElement('div');d.className='day';const h=Math.max(2,Math.round((v/max)*92));d.innerHTML=`<em>${fmt(v,1)}</em><div class="bartrack"><div class="barfill" style="height:${h}px"></div></div><small>${i===0?'วันนี้':'+'+i+' วัน'}</small>`;$('#sevenDayBars').appendChild(d)})}
function renderConfidence(p){if(p.recurrence!=null){$('#confidenceLabel').textContent='มีข้อมูลความถี่จากต้นแบบ';$('#confidenceText').textContent=(p.events||[]).length?'มีทั้งจำนวนครั้งและรายละเอียดเหตุการณ์บางปี แต่ยังไม่ใช่ฐานข้อมูลทางการครบถ้วน':'มีจำนวนครั้งท่วมซ้ำ แต่รายละเอียดปี/ความเสียหายยังไม่ครบ จึงต้องเชื่อมฐานข้อมูล ปภ. / GISTDA / ThaiWater เพิ่ม'}else{$('#confidenceLabel').textContent='ข้อมูลประวัติยังไม่พอ';$('#confidenceText').textContent='ห้ามตีความค่า “ไม่มีข้อมูล” ว่า “ไม่เคยท่วม” ต้องเพิ่มข้อมูลเหตุการณ์ย้อนหลังของจังหวัดนี้ก่อนใช้ตัดสินใจ'}}
function selectProvince(name,scroll=false){const p=state.history.find(x=>x.name===name);if(!p)return;state.selected=p;localStorage.setItem('thaiflood:intel:selected',name);$('#provinceSearch').value='';$('#searchResults').hidden=true;renderProvince();if(scroll)$('#province').scrollIntoView({behavior:'smooth',block:'start'})}
function renderSearch(q){const box=$('#searchResults');if(!q){box.hidden=true;return}const term=normalize(q);const rows=state.history.filter(p=>normalize(p.name).includes(term)||normalize(p.region).includes(term)||(p.hotspots||[]).some(x=>normalize(x).includes(term))).slice(0,14);box.innerHTML='';if(!rows.length)box.innerHTML='<div class="search-item"><span>ไม่พบพื้นที่ที่ค้นหา</span></div>';else rows.forEach(p=>{const b=document.createElement('button');b.className='search-item';b.innerHTML=`<b>${p.name}${p.hotspots.length?' • '+p.hotspots.join(', '):''}</b><span>${p.recurrence==null?'ยังไม่มีความถี่ในชุดอ้างอิง':p.recurrence+' ครั้ง / 11 ปี'}</span>`;b.onclick=()=>selectProvince(p.name,true);box.appendChild(b)});box.hidden=false}
$('.mini-tabs').addEventListener('click',e=>{const b=e.target.closest('.tab-btn');if(!b)return;document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab'+b.dataset.tab[0].toUpperCase()+b.dataset.tab.slice(1)).classList.add('active')});
$('#provinceSearch').addEventListener('input',e=>renderSearch(e.target.value));$('#provinceSearch').addEventListener('focus',e=>{if(e.target.value)renderSearch(e.target.value)});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('#searchResults').hidden=true});
$('#recurringOnlyBtn').onclick=()=>{state.recurringOnly=!state.recurringOnly;$('#recurringOnlyBtn').classList.toggle('active',state.recurringOnly)};
$('#regionFilter').onchange=e=>{state.filters.region=e.target.value;renderRanking();renderMap()};$('#frequencyFilter').onchange=e=>{state.filters.freq=e.target.value;renderRanking();renderMap()};$('#mechanismFilter').onchange=e=>{state.filters.mechanism=e.target.value;renderRanking();renderMap()};$('#resetFilters').onclick=()=>{state.filters={region:'all',freq:'all',mechanism:'all'};$('#regionFilter').value='all';$('#frequencyFilter').value='all';$('#mechanismFilter').value='all';renderRanking();renderMap()};$('#refreshBtn').onclick=()=>loadAll(true);$('#errorRetry').onclick=()=>loadAll(true);
loadAll();setInterval(()=>loadAll(true),30*60*1000);
